'use client'

import { useState } from 'react'
import { Minus, Plus, ShoppingBag, Trash2, X } from 'lucide-react'
import { useCart } from '@/lib/cart-context'
import { useLanguage } from '@/lib/language-context'
import { formatPrice, lineSubtotal } from '@/lib/types'
import { buildOrderMessage, buildWhatsAppUrl } from '@/lib/whatsapp'

export function CartDrawer() {
  const { lines, updateQuantity, removeLine, itemCount, total } = useCart()
  const { t, language, itemName, ingredientName } = useLanguage()
  const [open, setOpen] = useState(false)
  const [customerName, setCustomerName] = useState('')
  const [mode, setMode] = useState<'sur-place' | 'a-emporter'>('a-emporter')
  const handleOrder = () => window.open(buildWhatsAppUrl(buildOrderMessage(lines, customerName, mode, language)), '_blank', 'noopener,noreferrer')

  return <>
    {itemCount > 0 && !open ? <button type="button" onClick={() => setOpen(true)} className="fixed bottom-5 end-5 z-40 flex min-h-14 items-center gap-3 rounded-full bg-foreground px-5 text-background shadow-xl transition-transform active:scale-95" aria-label={t('cart.open', { count: itemCount, total: formatPrice(total) })}><span className="relative"><ShoppingBag className="size-6" aria-hidden="true" /><span className="absolute -end-2 -top-2 flex size-5 items-center justify-center rounded-full bg-primary text-xs font-bold text-primary-foreground" dir="ltr">{itemCount}</span></span><span className="font-display text-base font-bold" dir="ltr">{formatPrice(total)}</span></button> : null}
    {open ? <div className="fixed inset-0 z-50" role="dialog" aria-modal="true" aria-label={t('cart.title')}><button type="button" className="absolute inset-0 bg-black/50" onClick={() => setOpen(false)} aria-label={t('cart.close')} /><div className="absolute inset-x-0 bottom-0 flex max-h-[90dvh] flex-col rounded-t-3xl bg-card shadow-2xl">
      <div className="flex items-center justify-between border-b border-border p-4"><h2 className="font-display text-xl font-bold text-card-foreground">{t('cart.title')}</h2><button type="button" onClick={() => setOpen(false)} className="flex size-11 items-center justify-center rounded-full bg-muted text-muted-foreground" aria-label={t('customize.close')}><X className="size-5" aria-hidden="true" /></button></div>
      <div className="flex-1 overflow-y-auto p-4">{lines.length === 0 ? <p className="py-8 text-center text-muted-foreground">{t('cart.empty')}</p> : <ul className="flex flex-col gap-4">{lines.map((line) => { const removed = line.ingredients.filter((choice) => choice.quantity === 0); const added = line.ingredients.filter((choice) => choice.quantity > 1); const name = itemName(line.item); return <li key={line.uid} className="rounded-2xl border border-border p-3"><div className="flex items-start justify-between gap-2"><div className="min-w-0"><p className="font-semibold text-card-foreground">{name}</p>{line.bread ? <p className="text-sm text-muted-foreground">{t('cart.bread')}: {ingredientName(line.bread)}</p> : null}{removed.length ? <p className="text-sm text-muted-foreground">{t('cart.without')}: {removed.map((choice) => ingredientName(choice.ingredient)).join(', ')}</p> : null}{added.length ? <p className="text-sm text-muted-foreground">{t('cart.extra')}: {added.map((choice) => `${ingredientName(choice.ingredient)} ×${choice.quantity}`).join(', ')}</p> : null}{line.extras.length ? <p className="text-sm text-muted-foreground">{line.extras.map(ingredientName).join(', ')}</p> : null}</div><button type="button" onClick={() => removeLine(line.uid)} className="flex size-10 shrink-0 items-center justify-center rounded-full text-destructive" aria-label={t('cart.remove', { name })}><Trash2 className="size-4" aria-hidden="true" /></button></div><div className="mt-2 flex items-center justify-between"><div className="flex items-center gap-2" dir="ltr"><button type="button" onClick={() => updateQuantity(line.uid, line.quantity - 1)} className="flex size-10 items-center justify-center rounded-full bg-muted" aria-label={t('customize.decreaseQuantity')}><Minus className="size-4" aria-hidden="true" /></button><span className="w-6 text-center font-bold" aria-live="polite">{line.quantity}</span><button type="button" onClick={() => updateQuantity(line.uid, line.quantity + 1)} className="flex size-10 items-center justify-center rounded-full bg-muted" aria-label={t('customize.increaseQuantity')}><Plus className="size-4" aria-hidden="true" /></button></div><span className="font-display font-bold text-card-foreground" dir="ltr">{formatPrice(lineSubtotal(line))}</span></div></li> })}</ul>}</div>
      {lines.length ? <div className="flex flex-col gap-3 border-t border-border p-4 pb-[calc(1rem+env(safe-area-inset-bottom))]"><label className="flex flex-col gap-1.5"><span className="text-sm font-semibold text-card-foreground">{t('cart.name')}</span><input type="text" value={customerName} onChange={(event) => setCustomerName(event.target.value)} placeholder={t('cart.namePlaceholder')} className="min-h-12 rounded-2xl border-2 border-border bg-card px-4 text-base text-card-foreground placeholder:text-muted-foreground focus:border-primary focus:outline-none" /></label><div className="grid grid-cols-2 gap-2" role="radiogroup" aria-label={t('cart.mode')}>{(['sur-place', 'a-emporter'] as const).map((value) => <button key={value} type="button" role="radio" aria-checked={mode === value} onClick={() => setMode(value)} className={`min-h-12 rounded-2xl border-2 font-semibold transition-colors ${mode === value ? 'border-primary bg-accent text-accent-foreground' : 'border-border text-muted-foreground'}`}>{t(value === 'sur-place' ? 'cart.eatIn' : 'cart.takeaway')}</button>)}</div><div className="flex items-center justify-between px-1"><span className="text-muted-foreground">{t('cart.total')}</span><span className="font-display text-2xl font-black text-card-foreground" dir="ltr">{formatPrice(total)}</span></div><button type="button" onClick={handleOrder} className="flex min-h-14 w-full items-center justify-center gap-2 rounded-full bg-whatsapp font-bold text-whatsapp-foreground transition-transform active:scale-[0.98]"><svg viewBox="0 0 24 24" className="size-6 fill-current" aria-hidden="true"><path d="M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.52.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.669-.51-.173-.008-.371-.01-.57-.01-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347m-5.421 7.403h-.004a9.87 9.87 0 01-5.031-1.378l-.361-.214-3.741.982.998-3.648-.235-.374a9.86 9.86 0 01-1.51-5.26c.001-5.45 4.436-9.884 9.888-9.884 2.64 0 5.122 1.03 6.988 2.898a9.825 9.825 0 012.893 6.994c-.003 5.45-4.437 9.884-9.885 9.884" /></svg>{t('cart.order')}</button></div> : null}
    </div></div> : null}
  </>
}
